#spring:
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USER}
#    password: ${DB_PASS}
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: validate #Specifies hwo Hibernate should act w database.
#      show-sql: true
spring:
  profiles:
    active:
      - "@profileActive@"

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

server:
  error:
    include-stacktrace: never
